---
- name: install mariadb package (centOS)
  tags: centos,db,mariadb
  dnf:
    name: mariadb-server
    state: latest
    use_backend: dnf4
  when: ansible_distribution == "centOS"

- name: install mariadb package (Ubuntu)
  tags: db,mariadb,ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: "Mariadb - Restarting/Enabling"
  service:
    name: mariadb
    state: restarted
    enabled: true
